const products = [
  {
    Name: "Polo White Pent",
    slug: "polo-white-pent",
    category: "Pent",
    img: "/images/pic5.jpg",
    price: 800,
    available_total: 20,
    brand: "Polo",
    Rating: 5,
    number_reviews: 10,
    description: "Best white Summer Pent for men",
  },
  {
    Name: "J. Punjabi suit",
    slug: "j.-punjabi-suit",
    category: "Dress",
    img: "/images/pic22.jpg",
    price: 1500,
    available_total: 5,
    brand: "J.",
    Rating: 5,
    number_reviews: 30,
    description: "Best collection for women",
  },
  {
    Name: "Nike winter tracksuit",
    slug: "nike-winter-tracksuit",
    category: "Dress",
    img: "/images/pic19.jpg",
    price: 999,
    available_total: 12,
    brand: "Nike",
    Rating: 5,
    number_reviews: 7,
    description: "Best collection for men and women",
  },
  {
    Name: "Umair Collection",
    slug: "umair-collection",
    category: "Pair",
    img: "/images/pic6.jpg",
    price: 2000,
    available_total: 20,
    brand: "Umair",
    Rating: 3.5,
    number_reviews: 8,
    description: "Best collection women",
  },
  {
    Name: "Polo Pent/Shirt",
    slug: "polo-pent-shirt",
    category: "Pair",
    img: "/images/pic7.jpg",
    price: 3000,
    available_total: 20,
    brand: "Polo",
    Rating: 4,
    number_reviews: 7,
    description: "Best collection for men",
  },
  {
    Name: "Nike balck hoodie",
    slug: "nike-balck-hoodie",
    category: "Hoodie",
    img: "/images/pic16.jpg",
    price: 799,
    available_total: 20,
    brand: "Nike",
    Rating: 4.5,
    number_reviews: 12,
    description: "Best collection for men women and children",
  },
  {
    Name: "Polo Collection",
    slug: "polo-collection",
    category: "Pair",
    img: "/images/pic8.jpg",
    price: 3000,
    available_total: 20,
    brand: "Polo",
    Rating: 5,
    number_reviews: 6,
    description: "Best collection for women",
  },
  {
    Name: "Polo White Summer Shirt",
    slug: "polo-white-summer-shirt",
    category: "Shirts",
    img: "/images/pic1.jpg",
    price: 400,
    available_total: 20,
    brand: "Polo",
    Rating: 5,
    number_reviews: 12,
    description: "Best white Summer shirt for men",
  },
  {
    Name: "Nike Winter Pair",
    slug: "nike-winter-pair",
    category: "Pair",
    img: "/images/pic2.jpg",
    price: 700,
    available_total: 12,
    brand: "Nike",
    Rating: 4.5,
    number_reviews: 10,
    description: "Best Pair for men",
  },
  {
    Name: "J. White Summer Pair",
    slug: "j.-white-summer-pair",
    category: "Pair",
    img: "/images/pic3.jpg",
    price: 500,
    available_total: 10,
    brand: "J.",
    Rating: 3,
    number_reviews: 5,
    description: "Best white Summer Pair for women",
  },
  {
    Name: "UzairBrand collection",
    slug: "uzair-collection",
    category: "Pair",
    img: "/images/pic4.jpg",
    price: 1200,
    available_total: 13,
    brand: "UzairBrand",
    Rating: 4,
    number_reviews: 9,
    description: "Best collection for women",
  },
  {
    Name: "Nike Red Shirt",
    slug: "nike-red-shirt",
    category: "shirt",
    img: "/images/pic9.jpg",
    price: 500,
    available_total: 13,
    brand: "Nike",
    Rating: 4,
    number_reviews: 9,
    description: "Best collection for men",
  },
  {
    Name: "J. Jersey",
    slug: "J-Jersey",
    category: "Jersey",
    img: "/images/pic10.jpg",
    price: 800,
    available_total: 10,
    brand: "J.",
    Rating: 5,
    number_reviews: 12,
    description: "Best collection for men and women",
  },
  {
    Name: "Puma Pink Shirt",
    slug: "pink-shirt",
    category: "shirt",
    img: "/images/pic11.jpg",
    price: 600,
    available_total: 15,
    brand: "Puma",
    Rating: 4.5,
    number_reviews: 12,
    description: "Best collection for Women",
  },
  {
    Name: "Nike Sleeveless Shirt",
    slug: "nike-sleeveless-shirt",
    category: "shirt",
    img: "/images/pic12.jpg",
    price: 400,
    available_total: 10,
    brand: "Nike",
    Rating: 4,
    number_reviews: 12,
    description: "Beautiful Shirt for women",
  },
  {
    Name: "Jijo White Dress",
    slug: "jijo-white-dress",
    category: "Dress",
    img: "/images/pic13.jpg",
    price: 1000,
    available_total: 20,
    brand: "Jijo",
    Rating: 5,
    number_reviews: 20,
    description: "Best collection for women",
  },
  {
    Name: "Puma black Hoodie",
    slug: "puma-black-hoodie",
    category: "Hoodie",
    img: "/images/pic14.jpg",
    price: 900,
    available_total: 10,
    brand: "Puma",
    Rating: 5,
    number_reviews: 20,
    description: "Best collection for men and women",
  },
  {
    Name: "Outfiters black dress",
    slug: "outfiters-black-dress",
    category: "Dress",
    img: "/images/pic15.jpg",
    price: 999,
    available_total: 14,
    brand: "Outfiters",
    Rating: 4.5,
    number_reviews: 20,
    description: "Best collection for women",
  },
  {
    Name: "Polo sports tracksuit",
    slug: "polo-sports-tracksuit",
    category: "Dress",
    img: "/images/pic18.jpg",
    price: 999,
    available_total: 15,
    brand: "Polo",
    Rating: 5,
    number_reviews: 20,
    description: "Best collection for men",
  },

  {
    Name: "Outfiters beautiful pent shirt",
    slug: "outfiters-beautiful-pent-shirt",
    category: "Dress",
    img: "/images/pic20.jpg",
    price: 1200,
    available_total: 22,
    brand: "Outfiters",
    Rating: 4.5,
    number_reviews: 14,
    description: "Best collection for women",
  },
  {
    Name: "Jijo beautiful dress",
    slug: "jijo-beautiful-dress",
    category: "shirt",
    img: "/images/pic21.jpg",
    price: 1000,
    available_total: 5,
    brand: "Jijo",
    Rating: 5,
    number_reviews: 10,
    description: "Best collection for women",
  },
];

module.exports = products;
